#!/bin/bash
git remote set-url origin https://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@github.com/dejotaerre/p3e8b-tap-support
git add -A
git commit -a -m "+3E"

codigo_salida=$?

if [ $codigo_salida -eq 0 ]; then
    git push origin main
else
    echo "El comando falló con código de salida $codigo_salida."
fi